### ISSUE TITLE
help

### ISSUE THREAD

**Issue by abrorbekqakhkhorov** [Widiskel/telegram-query-getter-js#3]
Error reading sessions directory: ENOENT: no such file or directory, scandir 'C:\Users\User\Desktop\telegram-query-getter-js\sessions'
Unhandled Error:  Error: ENOENT: no such file or directory, scandir 'C:\Users\User\Desktop\telegram-query-getter-js\sessions'
    at Object.readdirSync (node:fs:1507:26)
    at Helper.getSession (file:///C:/Users/User/Desktop/telegram-query-getter-js/src/utils/helper.js:94:24)
    at onBoarding (file:///C:/Users/User/Desktop/telegram-query-getter-js/src/index.js:108:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///C:/Users/User/Desktop/telegram-query-getter-js/src/index.js:283:5 {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'C:\\Users\\User\\Desktop\\telegram-query-getter-js\\sessions'

**Comment by Widiskel** [comment]
follow the step by step guide
